version: "3"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
#    build:
#      context: ./nginx
#      dockerfile: ./nginx.Dockerfile
    ports:
      - 801:80
      - 4431:443
    volumes: # let the docker creates local folders. if i create empty local folders first, they will overwrite the nginx folders within the docker.
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/private
    links:
      - nest
      - vue
    depends_on:
      - nest
      - vue

  vue:
    build:
      context: ./worldmiao2/
      dockerfile: Dockerfile
    container_name: vue
    restart: always
    volumes:
#   mapping local dist directly to static serve folder in docker
      - ./worldmiao2/dist:/usr/share/nginx/html
    ports:
      - 90:80
    depends_on:
      - nest
    links:
      - nest

  nest:
    build:
      context: ./scraping-center/
      dockerfile: ./docker/App.Dockerfile
    container_name: nest
    volumes:
      - ./scraping-center/:/var/www/app:cached
      - ./scraping-center/src:/var/www/app/src
      - /var/www/app/node_modules # anonymous volume for node_modules only
    ports:
      - 9000:3000
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
#    no NEED TO connect from deploy machine. enable for local connection
    ports:
      - "6033:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
